package constants

const (
	COLUMN_USERNAME_SIZE = 32
	COLUMN_EMAIL_SIZE    = 255
	PAGE_SIZE            = 4096
	TABLE_MAX_PAGES      = 100
	ID_SIZE              = 4 // size of uint32
	ROW_SIZE             = ID_SIZE + COLUMN_USERNAME_SIZE + COLUMN_EMAIL_SIZE
	ROWS_PER_PAGE        = PAGE_SIZE / ROW_SIZE
	TABLE_MAX_ROWS       = ROWS_PER_PAGE * TABLE_MAX_PAGES
)
