services:
  toydb:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    working_dir: /app
    command: ["./toydb"]

  toydb-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    working_dir: /app
    command: ["go", "run", "main.go", "mydb.db"]
