# Simple Dockerfile for development
FROM golang:1.21-alpine

# Set working directory
WORKDIR /app

# Copy source code
COPY . .

RUN go format ./...
RUN go build -o main .

# Build and run the application
CMD ["./main"]
